version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: futbol_db
      POSTGRES_USER: futbol_user
      POSTGRES_PASSWORD: futbol_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
