version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: "no"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db/mydatabase
      DJANGO_SETTINGS_MODULE: app.settings
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "80:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
